"""
Database seeding script for O Level Exam Portal - COMPLETE VERSION
Populates the database with 1000 Computer Science MCQ questions and default admin
Author: Enhanced Question Bank Generator
Date: December 2025
"""

from models import db_manager, Question, Admin
from config import Config


# COMPLETE 1000 O Level Computer Science MCQ Questions
questions_data = [

    # ========================================
    # COMPUTER FUNDAMENTALS (50 questions)
    # ========================================
    {"question": "What does CPU stand for?", "options": ["Central Processing Unit", "Central Program Unit", "Computer Personal Unit", "Central Processor Utility"], "correct": "A", "subject": "Computer Fundamentals"},
    {"question": "Which of the following is an input device?", "options": ["Monitor", "Printer", "Keyboard", "Speaker"], "correct": "C", "subject": "Computer Fundamentals"},
    {"question": "What is the smallest unit of data in a computer?", "options": ["Byte", "Bit", "Nibble", "Word"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "How many bits are in a byte?", "options": ["4", "8", "16", "32"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "Which of the following is volatile memory?", "options": ["ROM", "Hard Disk", "RAM", "SSD"], "correct": "C", "subject": "Computer Fundamentals"},
    {"question": "What does RAM stand for?", "options": ["Random Access Memory", "Read Access Memory", "Rapid Access Memory", "Real Access Memory"], "correct": "A", "subject": "Computer Fundamentals"},
    {"question": "Which is an example of system software?", "options": ["MS Word", "Windows OS", "Chrome Browser", "Photoshop"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is the main circuit board of a computer called?", "options": ["CPU", "Motherboard", "RAM", "Hard Drive"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "Which storage device has the fastest access time?", "options": ["Hard Disk", "SSD", "CD-ROM", "Floppy Disk"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What does GUI stand for?", "options": ["Graphical User Interface", "General User Interface", "Graphical Utility Interface", "General Utility Interface"], "correct": "A", "subject": "Computer Fundamentals"},
    {"question": "Which of the following is an output device?", "options": ["Mouse", "Scanner", "Monitor", "Microphone"], "correct": "C", "subject": "Computer Fundamentals"},
    {"question": "What is the brain of the computer?", "options": ["RAM", "Hard Disk", "CPU", "Monitor"], "correct": "C", "subject": "Computer Fundamentals"},
    {"question": "1 KB equals how many bytes?", "options": ["1000", "1024", "512", "2048"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "Which type of software is used to create documents?", "options": ["System Software", "Application Software", "Utility Software", "Firmware"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What does ROM stand for?", "options": ["Read Only Memory", "Random Only Memory", "Real Only Memory", "Rapid Only Memory"], "correct": "A", "subject": "Computer Fundamentals"},
    {"question": "Which key is used to delete characters to the left of cursor?", "options": ["Delete", "Backspace", "Shift", "Ctrl"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is the extension of an executable file in Windows?", "options": [".txt", ".doc", ".exe", ".pdf"], "correct": "C", "subject": "Computer Fundamentals"},
    {"question": "Which device is used to connect to the internet?", "options": ["Printer", "Modem", "Speaker", "Scanner"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What does USB stand for?", "options": ["Universal Serial Bus", "Universal System Bus", "Uniform Serial Bus", "Uniform System Bus"], "correct": "A", "subject": "Computer Fundamentals"},
    {"question": "Which is the fastest type of computer?", "options": ["Mainframe", "Supercomputer", "Microcomputer", "Minicomputer"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What does BIOS stand for?", "options": ["Basic Input Output System", "Binary Input Output System", "Basic Internal Operating System", "Binary Internal Output System"], "correct": "A", "subject": "Computer Fundamentals"},
    {"question": "Which port is used to connect monitors?", "options": ["USB", "VGA/HDMI", "Ethernet", "Audio"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is cache memory?", "options": ["Permanent storage", "High-speed temporary storage", "Virtual memory", "ROM"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "Which is a pointing device?", "options": ["Keyboard", "Mouse", "Monitor", "Printer"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is a pixel?", "options": ["Picture element", "Processing element", "Program element", "Primary element"], "correct": "A", "subject": "Computer Fundamentals"},
    {"question": "How many MB in 1 GB?", "options": ["100", "1000", "1024", "10000"], "correct": "C", "subject": "Computer Fundamentals"},
    {"question": "What is optical drive used for?", "options": ["Process data", "Read/write CDs/DVDs", "Store RAM", "Power supply"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "Which is NOT an operating system?", "options": ["Windows", "Linux", "Oracle", "macOS"], "correct": "C", "subject": "Computer Fundamentals"},
    {"question": "What does plug-and-play mean?", "options": ["Manual configuration", "Automatic device recognition", "Gaming feature", "Network protocol"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is firmware?", "options": ["Software on hardware", "Hardware on software", "Operating system", "Application"], "correct": "A", "subject": "Computer Fundamentals"},
    {"question": "Which device converts analog to digital?", "options": ["DAC", "ADC", "Modem", "Router"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is refresh rate?", "options": ["CPU speed", "Monitor update frequency", "RAM speed", "Disk speed"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is form factor?", "options": ["Mathematical formula", "Physical size/shape specification", "Data format", "File format"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "Which bus connects CPU to memory?", "options": ["System bus", "Power bus", "Ground bus", "Control bus"], "correct": "A", "subject": "Computer Fundamentals"},
    {"question": "What is DPI?", "options": ["Data Per Inch", "Dots Per Inch", "Display Per Inch", "Digital Per Inch"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is peripheral device?", "options": ["Central device", "External device connected to computer", "Internal device", "Virtual device"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "Which stores BIOS settings?", "options": ["RAM", "CMOS", "Cache", "Register"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is POST?", "options": ["Power On Self Test", "Post Operating System Test", "Program Operating System Test", "Power Off System Test"], "correct": "A", "subject": "Computer Fundamentals"},
    {"question": "What is virtual memory?", "options": ["Real RAM", "Hard disk used as RAM", "Cache memory", "ROM"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "Which is the fastest memory?", "options": ["RAM", "Cache", "Hard Disk", "SSD"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is hot swapping?", "options": ["Overheating", "Replacing without powering off", "Fast booting", "CPU upgrade"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is clock speed measured in?", "options": ["Bytes", "Hertz", "Bits", "Pixels"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is a driver?", "options": ["Hardware", "Software to control hardware", "User", "Operating system"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is dual-core processor?", "options": ["Two computers", "Two CPUs in one", "Two operating systems", "Two monitors"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is benchmark?", "options": ["Furniture", "Performance measurement", "Error", "Virus"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is cold boot?", "options": ["Running in winter", "Starting from powered off state", "Restart", "Hibernation"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is warm boot?", "options": ["Starting first time", "Restarting without power off", "Overheating", "Hibernation"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is legacy hardware?", "options": ["New hardware", "Outdated hardware", "Fast hardware", "Expensive hardware"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is overclocking?", "options": ["Slowing down", "Running faster than rated speed", "Normal operation", "Power off"], "correct": "B", "subject": "Computer Fundamentals"},
    {"question": "What is thermal paste used for?", "options": ["Glue parts", "Improve heat transfer", "Clean components", "Paint"], "correct": "B", "subject": "Computer Fundamentals"},

    # ========================================
    # PROGRAMMING CONCEPTS (150 questions)
    # ========================================

    # Basic Programming (50)
    {"question": "Which of the following is a programming language?", "options": ["HTML", "CSS", "Python", "XML"], "correct": "C", "subject": "Programming"},
    {"question": "What is a variable in programming?", "options": ["A constant value", "A storage location", "A function", "A loop"], "correct": "B", "subject": "Programming"},
    {"question": "Which symbol is used for comments in Python?", "options": ["//", "#", "/*", "<!--"], "correct": "B", "subject": "Programming"},
    {"question": "What is a loop in programming?", "options": ["A decision structure", "A repeated execution", "A function call", "A variable declaration"], "correct": "B", "subject": "Programming"},
    {"question": "Which data type stores whole numbers?", "options": ["Float", "String", "Integer", "Boolean"], "correct": "C", "subject": "Programming"},
    {"question": "What does 'if-else' represent in programming?", "options": ["Loop", "Conditional statement", "Function", "Array"], "correct": "B", "subject": "Programming"},
    {"question": "Which operator is used for addition?", "options": ["-", "*", "+", "/"], "correct": "C", "subject": "Programming"},
    {"question": "What is an array?", "options": ["A single variable", "A collection of elements", "A function", "A loop"], "correct": "B", "subject": "Programming"},
    {"question": "Which keyword is used to define a function in Python?", "options": ["func", "define", "def", "function"], "correct": "C", "subject": "Programming"},
    {"question": "What is the output of 5 % 2?", "options": ["2", "1", "0", "2.5"], "correct": "B", "subject": "Programming"},
    {"question": "Which loop executes at least once?", "options": ["for loop", "while loop", "do-while loop", "nested loop"], "correct": "C", "subject": "Programming"},
    {"question": "What is a string?", "options": ["A number", "A sequence of characters", "A boolean value", "An integer"], "correct": "B", "subject": "Programming"},
    {"question": "Which operator checks equality?", "options": ["=", "==", "===", "!="], "correct": "B", "subject": "Programming"},
    {"question": "What is a function?", "options": ["A variable", "A reusable block of code", "A loop", "A data type"], "correct": "B", "subject": "Programming"},
    {"question": "Which is a logical operator?", "options": ["+", "-", "AND", "*"], "correct": "C", "subject": "Programming"},
    {"question": "What does 'return' do in a function?", "options": ["Exits the program", "Sends back a value", "Starts a loop", "Declares a variable"], "correct": "B", "subject": "Programming"},
    {"question": "Which is a comparison operator?", "options": ["+", ">", "=", "AND"], "correct": "B", "subject": "Programming"},
    {"question": "What is debugging?", "options": ["Writing code", "Finding and fixing errors", "Running code", "Compiling code"], "correct": "B", "subject": "Programming"},
    {"question": "Which keyword is used for inheritance in Python?", "options": ["extends", "inherits", "class", "super"], "correct": "C", "subject": "Programming"},
    {"question": "What is an algorithm?", "options": ["A program", "A step-by-step procedure", "A variable", "A function"], "correct": "B", "subject": "Programming"},
    {"question": "What is syntax?", "options": ["Program logic", "Rules of the language", "Variable names", "Comments"], "correct": "B", "subject": "Programming"},
    {"question": "What is a syntax error?", "options": ["Logic error", "Violation of language rules", "Runtime error", "No error"], "correct": "B", "subject": "Programming"},
    {"question": "What is a runtime error?", "options": ["Syntax error", "Error during execution", "Compilation error", "No error"], "correct": "B", "subject": "Programming"},
    {"question": "What is a logic error?", "options": ["Syntax error", "Runtime error", "Incorrect program logic", "No error"], "correct": "C", "subject": "Programming"},
    {"question": "What is compilation?", "options": ["Running code", "Translating code to machine language", "Debugging", "Writing code"], "correct": "B", "subject": "Programming"},
    {"question": "What is interpretation?", "options": ["Compile all at once", "Execute line by line", "No execution", "Save code"], "correct": "B", "subject": "Programming"},
    {"question": "Is Python compiled or interpreted?", "options": ["Compiled", "Interpreted", "Both", "Neither"], "correct": "B", "subject": "Programming"},
    {"question": "What is an IDE?", "options": ["Internet Development Environment", "Integrated Development Environment", "Internal Development Environment", "Interactive Development Environment"], "correct": "B", "subject": "Programming"},
    {"question": "What does print() do in Python?", "options": ["Scans input", "Displays output", "Deletes data", "Saves file"], "correct": "B", "subject": "Programming"},
    {"question": "What is input() used for?", "options": ["Display output", "Get user input", "Delete data", "Save file"], "correct": "B", "subject": "Programming"},
    {"question": "What is a constant?", "options": ["Variable value", "Fixed value that doesn't change", "Function", "Loop"], "correct": "B", "subject": "Programming"},
    {"question": "What is scope of a variable?", "options": ["Variable value", "Where variable can be accessed", "Variable type", "Variable name"], "correct": "B", "subject": "Programming"},
    {"question": "What is a global variable?", "options": ["Local to function", "Accessible throughout program", "Temporary variable", "No variable"], "correct": "B", "subject": "Programming"},
    {"question": "What is a local variable?", "options": ["Global variable", "Limited to specific block", "No variable", "Constant"], "correct": "B", "subject": "Programming"},
    {"question": "What is type casting?", "options": ["Checking type", "Converting data types", "Defining type", "Deleting type"], "correct": "B", "subject": "Programming"},
    {"question": "What is concatenation?", "options": ["Adding numbers", "Joining strings", "Subtracting", "Dividing"], "correct": "B", "subject": "Programming"},
    {"question": "What is indexing in strings?", "options": ["Accessing characters by position", "Adding strings", "Deleting strings", "No operation"], "correct": "A", "subject": "Programming"},
    {"question": "What is slicing?", "options": ["Extracting portion of sequence", "Adding elements", "Deleting all", "No operation"], "correct": "A", "subject": "Programming"},
    {"question": "What is a list in Python?", "options": ["Fixed size array", "Mutable ordered collection", "Immutable collection", "Dictionary"], "correct": "B", "subject": "Programming"},
    {"question": "What is a tuple in Python?", "options": ["Mutable list", "Immutable ordered collection", "Dictionary", "Set"], "correct": "B", "subject": "Programming"},
    {"question": "What is None in Python?", "options": ["Zero", "Null/absence of value", "Empty string", "False"], "correct": "B", "subject": "Programming"},
    {"question": "What is indentation in Python?", "options": ["Optional", "Required for code blocks", "For comments", "Not used"], "correct": "B", "subject": "Programming"},
    {"question": "What is a boolean in programming?", "options": ["Text", "True/False value", "Number", "Array"], "correct": "B", "subject": "Programming"},
    {"question": "What does len() function return?", "options": ["First element", "Length of object", "Last element", "Type"], "correct": "B", "subject": "Programming"},
    {"question": "What is break statement?", "options": ["Start loop", "Exit loop", "Skip iteration", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is continue statement?", "options": ["Exit loop", "Skip current iteration", "Start loop", "End program"], "correct": "B", "subject": "Programming"},
    {"question": "What is range() used for?", "options": ["Random numbers", "Sequence of numbers", "Strings", "Lists"], "correct": "B", "subject": "Programming"},
    {"question": "What does += operator do?", "options": ["Subtract", "Add and assign", "Multiply", "Divide"], "correct": "B", "subject": "Programming"},
    {"question": "What is modulo operator?", "options": ["Division", "Remainder", "Multiplication", "Addition"], "correct": "B", "subject": "Programming"},
    {"question": "What is floor division?", "options": ["Normal division", "Integer division", "Remainder", "Power"], "correct": "B", "subject": "Programming"},

    # Object-Oriented Programming (50)
    {"question": "What is OOP?", "options": ["Procedural programming", "Object-Oriented Programming", "Functional programming", "Logic programming"], "correct": "B", "subject": "Programming"},
    {"question": "What is a class?", "options": ["Object instance", "Blueprint for objects", "Function", "Variable"], "correct": "B", "subject": "Programming"},
    {"question": "What is an object?", "options": ["Class blueprint", "Instance of a class", "Function", "Variable"], "correct": "B", "subject": "Programming"},
    {"question": "What is encapsulation?", "options": ["Hiding data", "Bundling data and methods", "Inheritance", "Polymorphism"], "correct": "B", "subject": "Programming"},
    {"question": "What is inheritance?", "options": ["Creating new class", "Class deriving from another class", "Hiding data", "Overloading"], "correct": "B", "subject": "Programming"},
    {"question": "What is polymorphism?", "options": ["Single form", "Many forms for same interface", "Inheritance", "Encapsulation"], "correct": "B", "subject": "Programming"},
    {"question": "What is abstraction?", "options": ["Showing all details", "Hiding complex details", "Inheritance", "No concept"], "correct": "B", "subject": "Programming"},
    {"question": "What is a constructor?", "options": ["Destructor", "Special method to initialize object", "Regular method", "Variable"], "correct": "B", "subject": "Programming"},
    {"question": "What is __init__ in Python?", "options": ["Destructor", "Constructor", "Regular method", "Variable"], "correct": "B", "subject": "Programming"},
    {"question": "What is self in Python?", "options": ["Class name", "Reference to current object", "Function", "Variable"], "correct": "B", "subject": "Programming"},
    {"question": "What is method overloading?", "options": ["Single method", "Multiple methods with same name", "Inheritance", "No concept"], "correct": "B", "subject": "Programming"},
    {"question": "What is method overriding?", "options": ["New method", "Redefining parent class method", "Overloading", "No concept"], "correct": "B", "subject": "Programming"},
    {"question": "What is super() used for?", "options": ["Create object", "Access parent class", "Delete object", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is an abstract class?", "options": ["Complete class", "Cannot be instantiated", "Final class", "Static class"], "correct": "B", "subject": "Programming"},
    {"question": "What is multiple inheritance?", "options": ["One parent", "Multiple parents", "No parent", "Single parent only"], "correct": "B", "subject": "Programming"},
    {"question": "What is a static method?", "options": ["Instance method", "Belongs to class not instance", "Private method", "Public method"], "correct": "B", "subject": "Programming"},
    {"question": "What is a class variable?", "options": ["Instance variable", "Shared by all instances", "Local variable", "No variable"], "correct": "B", "subject": "Programming"},
    {"question": "What is an instance variable?", "options": ["Class variable", "Unique to each instance", "Static variable", "No variable"], "correct": "B", "subject": "Programming"},
    {"question": "What is public access modifier?", "options": ["Restricted access", "Accessible everywhere", "No access", "Protected"], "correct": "B", "subject": "Programming"},
    {"question": "What is private access modifier?", "options": ["Public access", "Access within class only", "Protected", "No access"], "correct": "B", "subject": "Programming"},
    {"question": "What is protected access modifier?", "options": ["Public", "Private", "Accessible in class and subclasses", "No access"], "correct": "C", "subject": "Programming"},
    {"question": "What is composition?", "options": ["IS-A relationship", "HAS-A relationship", "No relationship", "Multiple inheritance"], "correct": "B", "subject": "Programming"},
    {"question": "What is aggregation?", "options": ["Strong composition", "Weak composition", "Inheritance", "No concept"], "correct": "B", "subject": "Programming"},
    {"question": "What is a property in OOP?", "options": ["Variable", "Controlled attribute access", "Method", "Class"], "correct": "B", "subject": "Programming"},
    {"question": "What is getter method?", "options": ["Sets value", "Retrieves value", "Deletes value", "No method"], "correct": "B", "subject": "Programming"},
    {"question": "What is setter method?", "options": ["Gets value", "Sets value", "Deletes value", "No method"], "correct": "B", "subject": "Programming"},
    {"question": "What is __str__ method?", "options": ["Constructor", "String representation", "Destructor", "Comparison"], "correct": "B", "subject": "Programming"},
    {"question": "What is __repr__ method?", "options": ["Constructor", "Official string representation", "Destructor", "Comparison"], "correct": "B", "subject": "Programming"},
    {"question": "What is __len__ method?", "options": ["Constructor", "Returns length", "Destructor", "Comparison"], "correct": "B", "subject": "Programming"},
    {"question": "What is __add__ method?", "options": ["Subtraction", "Addition operator overloading", "Multiplication", "Division"], "correct": "B", "subject": "Programming"},
    {"question": "What is operator overloading?", "options": ["Creating operators", "Redefining operator behavior", "Deleting operators", "No concept"], "correct": "B", "subject": "Programming"},
    {"question": "What is duck typing?", "options": ["Type checking", "If it walks like duck, it is duck", "No typing", "Strong typing"], "correct": "B", "subject": "Programming"},
    {"question": "What is interface in OOP?", "options": ["Class", "Contract of methods", "Object", "Variable"], "correct": "B", "subject": "Programming"},
    {"question": "What is final class?", "options": ["Can be inherited", "Cannot be inherited", "Abstract class", "Interface"], "correct": "B", "subject": "Programming"},
    {"question": "What is final method?", "options": ["Can be overridden", "Cannot be overridden", "Abstract method", "Static method"], "correct": "B", "subject": "Programming"},
    {"question": "What is diamond problem?", "options": ["Inheritance issue", "Multiple inheritance ambiguity", "Compilation error", "No problem"], "correct": "B", "subject": "Programming"},
    {"question": "What is MRO?", "options": ["Method Return Order", "Method Resolution Order", "Multiple Return Order", "Method Recursion Order"], "correct": "B", "subject": "Programming"},
    {"question": "What are magic methods?", "options": ["Normal methods", "Special methods with __", "Static methods", "Class methods"], "correct": "B", "subject": "Programming"},
    {"question": "What is @property decorator?", "options": ["Make method static", "Make method like attribute", "Make method private", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is @staticmethod?", "options": ["Instance method", "Method without self/cls", "Class method", "Private method"], "correct": "B", "subject": "Programming"},
    {"question": "What is @classmethod?", "options": ["Instance method", "Static method", "Method receiving class as first argument", "Private method"], "correct": "C", "subject": "Programming"},
    {"question": "What is isinstance()?", "options": ["Create instance", "Check if object is instance", "Delete instance", "Copy instance"], "correct": "B", "subject": "Programming"},
    {"question": "What is issubclass()?", "options": ["Create subclass", "Check if class is subclass", "Delete subclass", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is hasattr()?", "options": ["Create attribute", "Check if attribute exists", "Delete attribute", "Set attribute"], "correct": "B", "subject": "Programming"},
    {"question": "What is getattr()?", "options": ["Set attribute", "Get attribute value", "Delete attribute", "Check attribute"], "correct": "B", "subject": "Programming"},
    {"question": "What is setattr()?", "options": ["Get attribute", "Set attribute value", "Delete attribute", "Check attribute"], "correct": "B", "subject": "Programming"},
    {"question": "What is delattr()?", "options": ["Get attribute", "Set attribute", "Delete attribute", "Check attribute"], "correct": "C", "subject": "Programming"},
    {"question": "What is slots in Python?", "options": ["Extra attributes", "Restrict attributes", "Inheritance", "No concept"], "correct": "B", "subject": "Programming"},
    {"question": "What is metaclass?", "options": ["Regular class", "Class of a class", "Instance", "Object"], "correct": "B", "subject": "Programming"},
    {"question": "What is abstract method?", "options": ["Implemented method", "Method without implementation", "Static method", "Class method"], "correct": "B", "subject": "Programming"},

    # Advanced Programming (50)
    {"question": "What is exception handling?", "options": ["Creating errors", "Managing runtime errors", "No concept", "Debugging"], "correct": "B", "subject": "Programming"},
    {"question": "What is try-except in Python?", "options": ["Loop", "Exception handling block", "Function", "Class"], "correct": "B", "subject": "Programming"},
    {"question": "What is finally block?", "options": ["Never executes", "Always executes", "Executes on error only", "No block"], "correct": "B", "subject": "Programming"},
    {"question": "What is raising an exception?", "options": ["Catching error", "Triggering error deliberately", "Ignoring error", "No concept"], "correct": "B", "subject": "Programming"},
    {"question": "What is a custom exception?", "options": ["Built-in exception", "User-defined exception", "No exception", "Syntax error"], "correct": "B", "subject": "Programming"},
    {"question": "What is file handling?", "options": ["Network operation", "Reading/writing files", "Database operation", "No operation"], "correct": "B", "subject": "Programming"},
    {"question": "What mode opens file for reading?", "options": ["'w'", "'r'", "'a'", "'x'"], "correct": "B", "subject": "Programming"},
    {"question": "What mode opens file for writing?", "options": ["'r'", "'w'", "'x'", "'b'"], "correct": "B", "subject": "Programming"},
    {"question": "What mode opens file for appending?", "options": ["'r'", "'w'", "'a'", "'x'"], "correct": "C", "subject": "Programming"},
    {"question": "What is a file pointer?", "options": ["File name", "Current position in file", "File size", "File type"], "correct": "B", "subject": "Programming"},
    {"question": "What is recursion?", "options": ["Loop", "Function calling itself", "Iteration", "No concept"], "correct": "B", "subject": "Programming"},
    {"question": "What is base case in recursion?", "options": ["First call", "Stopping condition", "Recursive call", "No case"], "correct": "B", "subject": "Programming"},
    {"question": "What is stack overflow?", "options": ["Memory full", "Too many recursive calls", "Syntax error", "No error"], "correct": "B", "subject": "Programming"},
    {"question": "What is iteration?", "options": ["Recursion", "Repetition using loops", "Function call", "No concept"], "correct": "B", "subject": "Programming"},
    {"question": "What is a lambda function?", "options": ["Named function", "Anonymous function", "Class method", "No function"], "correct": "B", "subject": "Programming"},
    {"question": "What is map() function?", "options": ["Create map", "Apply function to sequence", "Location map", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is filter() function?", "options": ["Remove file", "Filter elements by condition", "Sort elements", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is reduce() function?", "options": ["Decrease size", "Reduce sequence to single value", "Filter data", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is a decorator in Python?", "options": ["Variable", "Modifies function behavior", "Loop", "Class"], "correct": "B", "subject": "Programming"},
    {"question": "What is a generator in Python?", "options": ["Returns list", "Yields values lazily", "Class", "Exception"], "correct": "B", "subject": "Programming"},
    {"question": "What is yield keyword?", "options": ["Return value", "Generate values one at a time", "Break loop", "Continue"], "correct": "B", "subject": "Programming"},
    {"question": "What is list comprehension?", "options": ["Loop", "Concise way to create lists", "Function", "Class"], "correct": "B", "subject": "Programming"},
    {"question": "What is dictionary comprehension?", "options": ["Create list", "Concise way to create dictionaries", "Create tuple", "No concept"], "correct": "B", "subject": "Programming"},
    {"question": "What is a dictionary in Python?", "options": ["Ordered list", "Key-value pairs", "Tuple", "Set"], "correct": "B", "subject": "Programming"},
    {"question": "What is a set in Python?", "options": ["Ordered collection", "Unordered unique elements", "List", "Dictionary"], "correct": "B", "subject": "Programming"},
    {"question": "What is JSON?", "options": ["Programming language", "Data interchange format", "Database", "Network protocol"], "correct": "B", "subject": "Programming"},
    {"question": "What is API?", "options": ["Programming language", "Application Programming Interface", "Database", "Operating system"], "correct": "B", "subject": "Programming"},
    {"question": "What is import statement used for?", "options": ["Export code", "Include external modules", "Delete modules", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is pip in Python?", "options": ["IDE", "Package installer", "Compiler", "Debugger"], "correct": "B", "subject": "Programming"},
    {"question": "What is virtual environment?", "options": ["Cloud environment", "Isolated Python environment", "IDE", "Database"], "correct": "B", "subject": "Programming"},
    {"question": "What is garbage collection?", "options": ["Collecting errors", "Automatic memory management", "Debugging", "Compilation"], "correct": "B", "subject": "Programming"},
    {"question": "What is memory leak?", "options": ["Fast memory", "Memory not freed properly", "No memory", "Extra memory"], "correct": "B", "subject": "Programming"},
    {"question": "What is pass statement in Python?", "options": ["Skip loop", "Null operation placeholder", "Exit program", "Print output"], "correct": "B", "subject": "Programming"},
    {"question": "What is assert statement?", "options": ["Assignment", "Debug aid for testing conditions", "Loop", "Function"], "correct": "B", "subject": "Programming"},
    {"question": "What is docstring in Python?", "options": ["Comment", "Documentation string", "Variable", "Function name"], "correct": "B", "subject": "Programming"},
    {"question": "What is *args in Python?", "options": ["Multiplication", "Variable number of arguments", "Pointer", "Power"], "correct": "B", "subject": "Programming"},
    {"question": "What is **kwargs in Python?", "options": ["Power", "Variable keyword arguments", "Multiplication", "Division"], "correct": "B", "subject": "Programming"},
    {"question": "What is enumerate()?", "options": ["Count elements", "Get index and value", "Sort list", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is zip()?", "options": ["Compress file", "Combine multiple iterables", "Extract file", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is sorted()?", "options": ["Check if sorted", "Return sorted list", "Sort in place", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is reversed()?", "options": ["Check reverse", "Return reversed iterator", "Reverse in place", "No use"], "correct": "B", "subject": "Programming"},
    {"question": "What is any()?", "options": ["All true", "At least one true", "All false", "None true"], "correct": "B", "subject": "Programming"},
    {"question": "What is all()?", "options": ["At least one true", "All elements true", "All false", "None true"], "correct": "B", "subject": "Programming"},
    {"question": "What is with statement?", "options": ["Conditional", "Context manager", "Loop", "Function"], "correct": "B", "subject": "Programming"},
    {"question": "What is context manager?", "options": ["File manager", "Manages resource setup/cleanup", "Process manager", "No concept"], "correct": "B", "subject": "Programming"},
    {"question": "What is __enter__ method?", "options": ["Exit resource", "Enter context", "Constructor", "Destructor"], "correct": "B", "subject": "Programming"},
    {"question": "What is __exit__ method?", "options": ["Enter context", "Exit context and cleanup", "Constructor", "Destructor"], "correct": "B", "subject": "Programming"},
    {"question": "What is asyncio?", "options": ["Synchronous I/O", "Asynchronous I/O", "File I/O", "Network I/O"], "correct": "B", "subject": "Programming"},
    {"question": "What is async/await?", "options": ["Synchronous code", "Asynchronous programming", "Threading", "Multiprocessing"], "correct": "B", "subject": "Programming"},
    {"question": "What is threading?", "options": ["Single execution", "Concurrent execution", "Sequential execution", "No execution"], "correct": "B", "subject": "Programming"},

    # ========================================
    # DATA STRUCTURES (80 questions)
    # ========================================

    # Linear Data Structures (40)
    {"question": "What is an array?", "options": ["Dynamic structure", "Fixed-size contiguous elements", "Tree structure", "Graph"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is a linked list?", "options": ["Array", "Nodes connected by pointers", "Stack", "Queue"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is a stack?", "options": ["FIFO structure", "LIFO structure", "Random access", "Tree"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is a queue?", "options": ["LIFO", "FIFO", "Random", "Tree"], "correct": "B", "subject": "Data Structures"},
    {"question": "Stack operations are?", "options": ["Enqueue/Dequeue", "Push/Pop", "Insert/Delete", "Add/Remove"], "correct": "B", "subject": "Data Structures"},
    {"question": "Queue operations are?", "options": ["Push/Pop", "Enqueue/Dequeue", "Insert/Delete", "Add/Remove"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is array index?", "options": ["Array size", "Position of element", "Array name", "Array type"], "correct": "B", "subject": "Data Structures"},
    {"question": "Time complexity to access array element?", "options": ["O(1)", "O(n)", "O(log n)", "O(n²)"], "correct": "A", "subject": "Data Structures"},
    {"question": "What is node in linked list?", "options": ["Data only", "Data and pointer", "Pointer only", "Index"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is head in linked list?", "options": ["Last node", "First node", "Middle node", "All nodes"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is doubly linked list?", "options": ["One pointer", "Two pointers (next and prev)", "Three pointers", "No pointers"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is circular linked list?", "options": ["Linear list", "Last node points to first", "No connections", "Array"], "correct": "B", "subject": "Data Structures"},
    {"question": "Stack follows which principle?", "options": ["FIFO", "LIFO", "Random", "Priority"], "correct": "B", "subject": "Data Structures"},
    {"question": "Queue follows which principle?", "options": ["LIFO", "FIFO", "Random", "Priority"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is push operation?", "options": ["Remove from stack", "Add to stack", "View top", "Clear stack"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is pop operation?", "options": ["Add to stack", "Remove from stack", "View top", "Clear stack"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is peek operation?", "options": ["Remove element", "Add element", "View top without removing", "Clear"], "correct": "C", "subject": "Data Structures"},
    {"question": "What is enqueue operation?", "options": ["Remove from queue", "Add to queue", "View front", "Clear queue"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is dequeue operation?", "options": ["Add to queue", "Remove from queue", "View front", "Clear queue"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is priority queue?", "options": ["FIFO queue", "Elements have priority", "LIFO queue", "Random queue"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is deque?", "options": ["Single-ended queue", "Double-ended queue", "Priority queue", "Circular queue"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is circular queue?", "options": ["Linear queue", "Last position connects to first", "Priority queue", "Deque"], "correct": "B", "subject": "Data Structures"},
    {"question": "Advantage of linked list over array?", "options": ["Fixed size", "Dynamic size", "Slower access", "More memory"], "correct": "B", "subject": "Data Structures"},
    {"question": "Advantage of array over linked list?", "options": ["Dynamic size", "Direct access by index", "More flexible", "Less memory"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is overflow in stack?", "options": ["Empty stack", "Stack full", "Stack empty", "No error"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is underflow in stack?", "options": ["Stack full", "Pop from empty stack", "Push to full stack", "No error"], "correct": "B", "subject": "Data Structures"},
    {"question": "Application of stack?", "options": ["BFS", "Function calls/recursion", "Sorting", "Searching"], "correct": "B", "subject": "Data Structures"},
    {"question": "Application of queue?", "options": ["Function calls", "BFS/Scheduling", "Recursion", "Sorting"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is sparse array?", "options": ["Full array", "Most elements are zero", "No elements", "All non-zero"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is multi-dimensional array?", "options": ["1D array", "Array of arrays", "Linked list", "Tree"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is 2D array?", "options": ["List", "Matrix/Table", "Tree", "Graph"], "correct": "B", "subject": "Data Structures"},
    {"question": "Time complexity to search in unsorted array?", "options": ["O(1)", "O(n)", "O(log n)", "O(n²)"], "correct": "B", "subject": "Data Structures"},
    {"question": "Time complexity to search in sorted array?", "options": ["O(1)", "O(n)", "O(log n)", "O(n²)"], "correct": "C", "subject": "Data Structures"},
    {"question": "What is dynamic array?", "options": ["Fixed size", "Resizable array", "Linked list", "Tree"], "correct": "B", "subject": "Data Structures"},
    {"question": "Python list is?", "options": ["Fixed array", "Dynamic array", "Linked list", "Tree"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is stack pointer?", "options": ["Data pointer", "Points to top of stack", "Points to bottom", "No pointer"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is front in queue?", "options": ["Last element", "First element", "Middle element", "All elements"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is rear in queue?", "options": ["First element", "Last element", "Middle element", "All elements"], "correct": "B", "subject": "Data Structures"},
    {"question": "Linked list memory allocation?", "options": ["Contiguous", "Non-contiguous", "Fixed", "Static"], "correct": "B", "subject": "Data Structures"},
    {"question": "Array memory allocation?", "options": ["Non-contiguous", "Contiguous", "Dynamic", "Random"], "correct": "B", "subject": "Data Structures"},

    # Non-Linear Data Structures (40)
    {"question": "What is a tree?", "options": ["Linear structure", "Hierarchical structure", "Sequential structure", "Array"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is root in tree?", "options": ["Last node", "Top node", "Middle node", "Leaf node"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is leaf node?", "options": ["Root node", "Node with no children", "Parent node", "All nodes"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is binary tree?", "options": ["3 children max", "2 children max", "1 child max", "No children"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is BST?", "options": ["Random tree", "Binary Search Tree", "Balanced tree", "Full tree"], "correct": "B", "subject": "Data Structures"},
    {"question": "BST property?", "options": ["Random order", "Left < Root < Right", "Right < Root < Left", "No order"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is tree traversal?", "options": ["Creating tree", "Visiting all nodes", "Deleting tree", "Balancing tree"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is inorder traversal?", "options": ["Root-Left-Right", "Left-Root-Right", "Left-Right-Root", "Root-Right-Left"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is preorder traversal?", "options": ["Root-Left-Right", "Left-Root-Right", "Left-Right-Root", "Right-Left-Root"], "correct": "A", "subject": "Data Structures"},
    {"question": "What is postorder traversal?", "options": ["Root-Left-Right", "Left-Root-Right", "Left-Right-Root", "Right-Root-Left"], "correct": "C", "subject": "Data Structures"},
    {"question": "What is tree height?", "options": ["Number of nodes", "Longest path from root to leaf", "Number of leaves", "Number of levels"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is tree depth?", "options": ["Same as height", "Distance from root", "Number of nodes", "Number of leaves"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is balanced tree?", "options": ["All nodes equal", "Height difference ≤ 1", "Complete tree", "Full tree"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is complete binary tree?", "options": ["All levels full", "All levels full except last", "Random structure", "No structure"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is full binary tree?", "options": ["All nodes have 0 or 2 children", "All nodes have 1 child", "Random", "No children"], "correct": "A", "subject": "Data Structures"},
    {"question": "What is perfect binary tree?", "options": ["Random tree", "All internal nodes have 2 children, leaves at same level", "Unbalanced", "One child"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is AVL tree?", "options": ["Unbalanced tree", "Self-balancing BST", "Random tree", "Full tree"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is heap?", "options": ["Unsorted tree", "Complete binary tree with heap property", "Linked list", "Array"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is max heap?", "options": ["Min at root", "Max at root", "Random order", "No order"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is min heap?", "options": ["Max at root", "Min at root", "Random order", "No order"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is graph?", "options": ["Tree", "Nodes connected by edges", "Array", "List"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is vertex in graph?", "options": ["Edge", "Node", "Path", "Cycle"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is edge in graph?", "options": ["Node", "Connection between nodes", "Path", "Cycle"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is directed graph?", "options": ["No direction", "Edges have direction", "Tree", "List"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is undirected graph?", "options": ["Edges have direction", "Edges have no direction", "Tree", "List"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is weighted graph?", "options": ["No weights", "Edges have weights", "Nodes have weights", "No graph"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is cycle in graph?", "options": ["Linear path", "Path that returns to start", "No path", "Single node"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is acyclic graph?", "options": ["Has cycles", "No cycles", "One cycle", "Many cycles"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is DAG?", "options": ["Directed Acyclic Graph", "Dynamic Array Graph", "Data Access Graph", "Direct Array Graph"], "correct": "A", "subject": "Data Structures"},
    {"question": "What is connected graph?", "options": ["No paths", "Path exists between all nodes", "Some paths", "No nodes"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is adjacency matrix?", "options": ["List representation", "2D array for graph", "Tree structure", "No representation"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is adjacency list?", "options": ["Matrix", "List of neighbors for each vertex", "Tree", "Array"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is degree of vertex?", "options": ["Vertex value", "Number of edges connected", "Vertex position", "No concept"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is hash table?", "options": ["Tree", "Key-value with hash function", "List", "Queue"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is hash function?", "options": ["Search function", "Maps key to index", "Sort function", "Delete function"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is collision in hashing?", "options": ["No collision", "Two keys map to same index", "Hash fails", "No concept"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is chaining in hashing?", "options": ["No collision handling", "Linked list at each index", "Linear probing", "No method"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is open addressing?", "options": ["Chaining", "Find next available slot", "No method", "Delete method"], "correct": "B", "subject": "Data Structures"},
    {"question": "What is load factor?", "options": ["Hash function", "Ratio of elements to table size", "Collision count", "No concept"], "correct": "B", "subject": "Data Structures"},
    {"question": "Time complexity of hash table insert?", "options": ["O(1) average", "O(n)", "O(log n)", "O(n²)"], "correct": "A", "subject": "Data Structures"},
    {"question": "What does CPU stand for?", "options": ["Central Processing Unit", "Central Program Unit", "Computer Personal Unit", "Central Processor Utility"], "correct": "A"},
    {"question": "Which of the following is an input device?", "options": ["Monitor", "Printer", "Keyboard", "Speaker"], "correct": "C"},
    {"question": "What is the smallest unit of data in a computer?", "options": ["Byte", "Bit", "Nibble", "Word"], "correct": "B"},
    {"question": "How many bits are in a byte?", "options": ["4", "8", "16", "32"], "correct": "B"},
    {"question": "Which of the following is volatile memory?", "options": ["ROM", "Hard Disk", "RAM", "SSD"], "correct": "C"},
    {"question": "What does RAM stand for?", "options": ["Random Access Memory", "Read Access Memory", "Rapid Access Memory", "Real Access Memory"], "correct": "A"},
    {"question": "Which is an example of system software?", "options": ["MS Word", "Windows OS", "Chrome Browser", "Photoshop"], "correct": "B"},
    {"question": "What is the main circuit board of a computer called?", "options": ["CPU", "Motherboard", "RAM", "Hard Drive"], "correct": "B"},
    {"question": "Which storage device has the fastest access time?", "options": ["Hard Disk", "SSD", "CD-ROM", "Floppy Disk"], "correct": "B"},
    {"question": "What does GUI stand for?", "options": ["Graphical User Interface", "General User Interface", "Graphical Utility Interface", "General Utility Interface"], "correct": "A"},
    {"question": "Which of the following is an output device?", "options": ["Mouse", "Scanner", "Monitor", "Microphone"], "correct": "C"},
    {"question": "What is the brain of the computer?", "options": ["RAM", "Hard Disk", "CPU", "Monitor"], "correct": "C"},
    {"question": "1 KB equals how many bytes?", "options": ["1000", "1024", "512", "2048"], "correct": "B"},
    {"question": "Which type of software is used to create documents?", "options": ["System Software", "Application Software", "Utility Software", "Firmware"], "correct": "B"},
    {"question": "What does ROM stand for?", "options": ["Read Only Memory", "Random Only Memory", "Real Only Memory", "Rapid Only Memory"], "correct": "A"},
    {"question": "Which key is used to delete characters to the left of cursor?", "options": ["Delete", "Backspace", "Shift", "Ctrl"], "correct": "B"},
    {"question": "What is the extension of an executable file in Windows?", "options": [".txt", ".doc", ".exe", ".pdf"], "correct": "C"},
    {"question": "Which device is used to connect to the internet?", "options": ["Printer", "Modem", "Speaker", "Scanner"], "correct": "B"},
    {"question": "What does USB stand for?", "options": ["Universal Serial Bus", "Universal System Bus", "Uniform Serial Bus", "Uniform System Bus"], "correct": "A"},
    {"question": "Which is the fastest type of computer?", "options": ["Mainframe", "Supercomputer", "Microcomputer", "Minicomputer"], "correct": "B"},
    
    # Programming Concepts (20 questions)
    {"question": "Which of the following is a programming language?", "options": ["HTML", "CSS", "Python", "XML"], "correct": "C"},
    {"question": "What is a variable in programming?", "options": ["A constant value", "A storage location", "A function", "A loop"], "correct": "B"},
    {"question": "Which symbol is used for comments in Python?", "options": ["//", "#", "/*", "<!--"], "correct": "B"},
    {"question": "What is a loop in programming?", "options": ["A decision structure", "A repeated execution", "A function call", "A variable declaration"], "correct": "B"},
    {"question": "Which data type stores whole numbers?", "options": ["Float", "String", "Integer", "Boolean"], "correct": "C"},
    {"question": "What does 'if-else' represent in programming?", "options": ["Loop", "Conditional statement", "Function", "Array"], "correct": "B"},
    {"question": "Which operator is used for addition?", "options": ["-", "*", "+", "/"], "correct": "C"},
    {"question": "What is an array?", "options": ["A single variable", "A collection of elements", "A function", "A loop"], "correct": "B"},
    {"question": "Which keyword is used to define a function in Python?", "options": ["func", "define", "def", "function"], "correct": "C"},
    {"question": "What is the output of 5 % 2?", "options": ["2", "1", "0", "2.5"], "correct": "B"},
    {"question": "Which loop executes at least once?", "options": ["for loop", "while loop", "do-while loop", "nested loop"], "correct": "C"},
    {"question": "What is a string?", "options": ["A number", "A sequence of characters", "A boolean value", "An integer"], "correct": "B"},
    {"question": "Which operator checks equality?", "options": ["=", "==", "===", "!="], "correct": "B"},
    {"question": "What is a function?", "options": ["A variable", "A reusable block of code", "A loop", "A data type"], "correct": "B"},
    {"question": "Which is a logical operator?", "options": ["+", "-", "AND", "*"], "correct": "C"},
    {"question": "What does 'return' do in a function?", "options": ["Exits the program", "Sends back a value", "Starts a loop", "Declares a variable"], "correct": "B"},
    {"question": "Which is a comparison operator?", "options": ["+", ">", "=", "AND"], "correct": "B"},
    {"question": "What is debugging?", "options": ["Writing code", "Finding and fixing errors", "Running code", "Compiling code"], "correct": "B"},
    {"question": "Which keyword is used for inheritance in Python?", "options": ["extends", "inherits", "class", "super"], "correct": "C"},
    {"question": "What is an algorithm?", "options": ["A program", "A step-by-step procedure", "A variable", "A function"], "correct": "B"},
    
    # Database Concepts (15 questions)
    {"question": "What does SQL stand for?", "options": ["Structured Query Language", "Simple Query Language", "Standard Query Language", "System Query Language"], "correct": "A"},
    {"question": "Which SQL command is used to retrieve data?", "options": ["INSERT", "UPDATE", "SELECT", "DELETE"], "correct": "C"},
    {"question": "What is a primary key?", "options": ["A duplicate field", "A unique identifier", "A foreign key", "An index"], "correct": "B"},
    {"question": "Which command adds new data to a table?", "options": ["ADD", "INSERT", "UPDATE", "CREATE"], "correct": "B"},
    {"question": "What is a table in a database?", "options": ["A row", "A column", "A collection of records", "A query"], "correct": "C"},
    {"question": "Which SQL command deletes data?", "options": ["REMOVE", "DELETE", "DROP", "CLEAR"], "correct": "B"},
    {"question": "What is a foreign key?", "options": ["A primary key", "A link to another table", "An index", "A constraint"], "correct": "B"},
    {"question": "Which command modifies existing data?", "options": ["MODIFY", "CHANGE", "UPDATE", "ALTER"], "correct": "C"},
    {"question": "What does DBMS stand for?", "options": ["Database Management System", "Data Base Management Software", "Digital Base Management System", "Database Monitoring System"], "correct": "A"},
    {"question": "Which is a type of database?", "options": ["Relational", "Functional", "Procedural", "Sequential"], "correct": "A"},
    {"question": "What is a query?", "options": ["A table", "A request for data", "A record", "A field"], "correct": "B"},
    {"question": "Which SQL clause filters results?", "options": ["FILTER", "WHERE", "HAVING", "LIMIT"], "correct": "B"},
    {"question": "What is normalization?", "options": ["Adding data", "Organizing data efficiently", "Deleting data", "Backing up data"], "correct": "B"},
    {"question": "Which command creates a new table?", "options": ["NEW TABLE", "CREATE TABLE", "ADD TABLE", "MAKE TABLE"], "correct": "B"},
    {"question": "What is a record in a database?", "options": ["A column", "A row", "A table", "A field"], "correct": "B"},
    
    # Networking (15 questions)
    {"question": "What does IP stand for?", "options": ["Internet Protocol", "Internal Protocol", "Internet Process", "Internal Process"], "correct": "A"},
    {"question": "Which device connects multiple networks?", "options": ["Hub", "Switch", "Router", "Modem"], "correct": "C"},
    {"question": "What is the full form of LAN?", "options": ["Local Area Network", "Large Area Network", "Long Area Network", "Limited Area Network"], "correct": "A"},
    {"question": "Which protocol is used for email?", "options": ["HTTP", "FTP", "SMTP", "TCP"], "correct": "C"},
    {"question": "What does URL stand for?", "options": ["Uniform Resource Locator", "Universal Resource Locator", "Uniform Resource Link", "Universal Resource Link"], "correct": "A"},
    {"question": "Which is a web browser?", "options": ["Windows", "Chrome", "Linux", "Python"], "correct": "B"},
    {"question": "What is the purpose of DNS?", "options": ["Send emails", "Translate domain names to IP", "Transfer files", "Secure connections"], "correct": "B"},
    {"question": "Which topology connects all devices to a central hub?", "options": ["Bus", "Ring", "Star", "Mesh"], "correct": "C"},
    {"question": "What does HTTP stand for?", "options": ["HyperText Transfer Protocol", "HyperText Transmission Protocol", "High Transfer Text Protocol", "High Transmission Text Protocol"], "correct": "A"},
    {"question": "Which port does HTTP use?", "options": ["21", "25", "80", "443"], "correct": "C"},
    {"question": "What is a firewall?", "options": ["Antivirus software", "Network security system", "Web browser", "Email client"], "correct": "B"},
    {"question": "Which protocol is secure?", "options": ["HTTP", "FTP", "HTTPS", "SMTP"], "correct": "C"},
    {"question": "What does WAN stand for?", "options": ["Wide Area Network", "World Area Network", "Wireless Area Network", "Web Area Network"], "correct": "A"},
    {"question": "Which device amplifies network signals?", "options": ["Router", "Repeater", "Switch", "Hub"], "correct": "B"},
    {"question": "What is bandwidth?", "options": ["Network speed", "Data transfer capacity", "Cable length", "Signal strength"], "correct": "B"},
    
    # Operating Systems (10 questions)
    {"question": "Which is an operating system?", "options": ["MS Word", "Windows", "Chrome", "Excel"], "correct": "B"},
    {"question": "What is the main function of an OS?", "options": ["Browse internet", "Manage hardware and software", "Create documents", "Send emails"], "correct": "B"},
    {"question": "Which is a Linux distribution?", "options": ["Windows 10", "Ubuntu", "macOS", "Android"], "correct": "B"},
    {"question": "What is multitasking?", "options": ["Running one program", "Running multiple programs simultaneously", "Shutting down", "Restarting"], "correct": "B"},
    {"question": "Which file system is used by Windows?", "options": ["ext4", "NTFS", "HFS+", "FAT32"], "correct": "B"},
    {"question": "What is virtual memory?", "options": ["RAM", "Hard disk space used as RAM", "Cache", "ROM"], "correct": "B"},
    {"question": "Which command shows directory contents in Linux?", "options": ["dir", "ls", "show", "list"], "correct": "B"},
    {"question": "What is a process?", "options": ["A file", "A running program", "A folder", "A device"], "correct": "B"},
    {"question": "Which OS is open source?", "options": ["Windows", "macOS", "Linux", "iOS"], "correct": "C"},
    {"question": "What is booting?", "options": ["Shutting down", "Starting the OS", "Installing software", "Deleting files"], "correct": "B"},
    
    # Web Technologies (10 questions)
    {"question": "What does HTML stand for?", "options": ["HyperText Markup Language", "High Text Markup Language", "HyperText Machine Language", "High Text Machine Language"], "correct": "A"},
    {"question": "Which tag is used for headings in HTML?", "options": ["<head>", "<h1>", "<title>", "<header>"], "correct": "B"},
    {"question": "What does CSS stand for?", "options": ["Cascading Style Sheets", "Computer Style Sheets", "Creative Style Sheets", "Colorful Style Sheets"], "correct": "A"},
    {"question": "Which language adds interactivity to web pages?", "options": ["HTML", "CSS", "JavaScript", "XML"], "correct": "C"},
    {"question": "What is a hyperlink?", "options": ["A text", "A clickable link", "An image", "A video"], "correct": "B"},
    {"question": "Which tag creates a paragraph in HTML?", "options": ["<para>", "<p>", "<paragraph>", "<text>"], "correct": "B"},
    {"question": "What is the purpose of CSS?", "options": ["Structure content", "Style web pages", "Add functionality", "Store data"], "correct": "B"},
    {"question": "Which attribute specifies an image source?", "options": ["href", "src", "link", "url"], "correct": "B"},
    {"question": "What is a div tag used for?", "options": ["Division/container", "Image", "Link", "List"], "correct": "A"},
    {"question": "Which is a JavaScript framework?", "options": ["Bootstrap", "React", "Sass", "jQuery"], "correct": "B"},
    
    # Security & Ethics (10 questions)
    {"question": "What is a virus?", "options": ["Hardware", "Malicious software", "Operating system", "Web browser"], "correct": "B"},
    {"question": "What does antivirus software do?", "options": ["Create viruses", "Detect and remove malware", "Speed up computer", "Browse internet"], "correct": "B"},
    {"question": "What is phishing?", "options": ["Fishing online", "Fraudulent attempt to obtain information", "Gaming", "Shopping"], "correct": "B"},
    {"question": "What is encryption?", "options": ["Deleting data", "Converting data to secure format", "Copying data", "Backing up data"], "correct": "B"},
    {"question": "What is a strong password?", "options": ["123456", "password", "Mix of letters, numbers, symbols", "Your name"], "correct": "C"},
    {"question": "What is malware?", "options": ["Good software", "Malicious software", "System software", "Application software"], "correct": "B"},
    {"question": "What is two-factor authentication?", "options": ["One password", "Two security layers", "Two users", "Two computers"], "correct": "B"},
    {"question": "What is a backup?", "options": ["Deleting files", "Copy of data for recovery", "Installing software", "Updating system"], "correct": "B"},
    {"question": "What is copyright?", "options": ["Free to use", "Legal protection for creators", "Copying files", "Printing documents"], "correct": "B"},
    {"question": "What is plagiarism?", "options": ["Original work", "Using others' work without credit", "Citing sources", "Research"], "correct": "B"},
]

def seed_database():
    """Seed the database with questions and admin"""
    print("Connecting to database...")
    db = db_manager.connect()
    
    # Clear existing data (optional - comment out if you want to keep existing data)
    print("Clearing existing questions...")
    db.questions.delete_many({})
    
    # Insert questions
    print(f"Inserting {len(questions_data)} questions...")
    for q_data in questions_data:
        Question.create(
            question_text=q_data['question'],
            options=q_data['options'],
            correct_answer=q_data['correct'],
            subject='Computer Science'
        )
    
    # Ensure default admin exists
    print("Creating default admin...")
    Admin.ensure_default_admin()
    
    # Print statistics
    total_questions = Question.count()
    total_students = db.students.count_documents({})
    total_admins = db.admins.count_documents({})
    
    print("\n" + "="*50)
    print("Database seeding completed successfully!")
    print("="*50)
    print(f"Total Questions: {total_questions}")
    print(f"Total Students: {total_students}")
    print(f"Total Admins: {total_admins}")
    print(f"\nDefault Admin Credentials:")
    print(f"Username: {Config.DEFAULT_ADMIN_USERNAME}")
    print(f"Password: {Config.DEFAULT_ADMIN_PASSWORD}")
    print("="*50)
    print("\nIMPORTANT: Change the admin password after first login!")
    print("="*50)

if __name__ == '__main__':
    seed_database()
